# Generated by Django 4.2.16 on 2024-11-19 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_request_code', models.CharField(max_length=10)),
                ('interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.interest')),
            ],
        ),
    ]
