# Generated by Django 4.2.16 on 2024-11-20 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_link_theme_industry'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='api_request_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='industry_codes',
            field=models.ManyToManyField(related_name='themes', to='stock.industrycode'),
        ),
    ]
